In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [4]:
x.grad

In [10]:
y = 2 * torch.dot(x,x)

In [11]:
y

tensor(28., grad_fn=<MulBackward0>)

In [12]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [13]:
y.backward()

In [15]:
x.grad

tensor([ 0.,  8., 16., 24.])

In [16]:
x.grad == 4 * x

tensor([ True, False, False, False])

In [17]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [18]:
y = x.sum()

In [19]:
y

tensor(6., grad_fn=<SumBackward0>)

In [20]:
y.backward()

In [21]:
x.grad

tensor([1., 1., 1., 1.])