In [1]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

In [3]:
num_inputs = 28*28
num_outputs = 10

In [4]:
W = torch.normal(0,0.01,size=(num_inputs,num_outputs),requires_grad=True)

In [5]:
b = torch.zeros(num_outputs,requires_grad=True)

In [6]:
X = torch.tensor([
    [1.0,2.0,3.0],
    [4.0,5.0,6.0]
])

X.sum(0,keepdim=True),X.sum(1,keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [7]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1,keepdim=True)
    return X_exp / partition

In [8]:
X = torch.normal(0, 1, (2, 5))
X_prob = softmax(X)

In [9]:
X_prob,X_prob.sum(1)

(tensor([[0.0644, 0.4312, 0.4038, 0.0364, 0.0642],
         [0.2243, 0.1437, 0.2578, 0.0673, 0.3070]]),
 tensor([1., 1.]))

In [10]:
def net(X):
    return softmax(torch.matmul(X.reshape((-1,W.shape[0])),W) + b)

In [13]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([
    [0.1, 0.3, 0.6],
    [0.3, 0.2, 0.5]
])
y_hat[[0, 1], y]

tensor([0.1000, 0.5000])